/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LeadershipTeamRouteImport } from './routes/leadership-team'
import { Route as OurAccomplishmentsRouteImport } from './routes/our-accomplishments'
import { Route as OurFoundersRouteImport } from './routes/our-founders'
import { Route as OurMissionRouteImport } from './routes/our-mission'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OurValuesRouteImport } from './routes/our-values'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipTeamRoute = LeadershipTeamRouteImport.update({
  id: '/leadership-team',
  path: '/leadership-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OurAccomplishmentsRoute = OurAccomplishmentsRouteImport.update({
  id: '/our-accomplishments',
  path: '/our-accomplishments',
  getParentRoute: () => rootRouteImport,
} as any)
const OurFoundersRoute = OurFoundersRouteImport.update({
  id: '/our-founders',
  path: '/our-founders',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMissionRoute = OurMissionRouteImport.update({
  id: '/our-mission',
  path: '/our-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OurValuesRoute = OurValuesRouteImport.update({
  id: '/our-values',
  path: '/our-values',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/journal': typeof JournalRoute
  '/leadership-team': typeof LeadershipTeamRoute
  '/our-accomplishments': typeof OurAccomplishmentsRoute
  '/our-founders': typeof OurFoundersRoute
  '/our-mission': typeof OurMissionRoute
  '/our-story': typeof OurStoryRoute
  '/our-values': typeof OurValuesRoute
  '/science': typeof ScienceRoute
  '/shop': typeof ShopRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-use': typeof TermsOfUseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/journal': typeof JournalRoute
  '/leadership-team': typeof LeadershipTeamRoute
  '/our-accomplishments': typeof OurAccomplishmentsRoute
  '/our-founders': typeof OurFoundersRoute
  '/our-mission': typeof OurMissionRoute
  '/our-story': typeof OurStoryRoute
  '/our-values': typeof OurValuesRoute
  '/science': typeof ScienceRoute
  '/shop': typeof ShopRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-use': typeof TermsOfUseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/journal': typeof JournalRoute
  '/leadership-team': typeof LeadershipTeamRoute
  '/our-accomplishments': typeof OurAccomplishmentsRoute
  '/our-founders': typeof OurFoundersRoute
  '/our-mission': typeof OurMissionRoute
  '/our-story': typeof OurStoryRoute
  '/our-values': typeof OurValuesRoute
  '/science': typeof ScienceRoute
  '/shop': typeof ShopRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-of-use': typeof TermsOfUseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/journal'
    | '/leadership-team'
    | '/our-accomplishments'
    | '/our-founders'
    | '/our-mission'
    | '/our-story'
    | '/our-values'
    | '/science'
    | '/shop'
    | '/terms-and-conditions'
    | '/terms-of-use'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/journal'
    | '/leadership-team'
    | '/our-accomplishments'
    | '/our-founders'
    | '/our-mission'
    | '/our-story'
    | '/our-values'
    | '/science'
    | '/shop'
    | '/terms-and-conditions'
    | '/terms-of-use'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/journal'
    | '/leadership-team'
    | '/our-accomplishments'
    | '/our-founders'
    | '/our-mission'
    | '/our-story'
    | '/our-values'
    | '/science'
    | '/shop'
    | '/terms-and-conditions'
    | '/terms-of-use'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRoute
  JournalRoute: typeof JournalRoute
  LeadershipTeamRoute: typeof LeadershipTeamRoute
  OurAccomplishmentsRoute: typeof OurAccomplishmentsRoute
  OurFoundersRoute: typeof OurFoundersRoute
  OurMissionRoute: typeof OurMissionRoute
  OurStoryRoute: typeof OurStoryRoute
  OurValuesRoute: typeof OurValuesRoute
  ScienceRoute: typeof ScienceRoute
  ShopRoute: typeof ShopRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-team': {
      id: '/leadership-team'
      path: '/leadership-team'
      fullPath: '/leadership-team'
      preLoaderRoute: typeof LeadershipTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-accomplishments': {
      id: '/our-accomplishments'
      path: '/our-accomplishments'
      fullPath: '/our-accomplishments'
      preLoaderRoute: typeof OurAccomplishmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-founders': {
      id: '/our-founders'
      path: '/our-founders'
      fullPath: '/our-founders'
      preLoaderRoute: typeof OurFoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-mission': {
      id: '/our-mission'
      path: '/our-mission'
      fullPath: '/our-mission'
      preLoaderRoute: typeof OurMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-values': {
      id: '/our-values'
      path: '/our-values'
      fullPath: '/our-values'
      preLoaderRoute: typeof OurValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRoute,
  JournalRoute: JournalRoute,
  LeadershipTeamRoute: LeadershipTeamRoute,
  OurAccomplishmentsRoute: OurAccomplishmentsRoute,
  OurFoundersRoute: OurFoundersRoute,
  OurMissionRoute: OurMissionRoute,
  OurStoryRoute: OurStoryRoute,
  OurValuesRoute: OurValuesRoute,
  ScienceRoute: ScienceRoute,
  ShopRoute: ShopRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TermsOfUseRoute: TermsOfUseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
